apiVersion: v1
kind: Service
metadata:
  name: todo-app
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-app
spec:
  selector:
    app.kubernetes.io/name: todo-app
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
